name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # CHANGE TO YOUR BRANCH
  push:
    branches: [ my-github-ci-cd ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Building docker images
        run: |
          cd app
          docker-compose build
          
  deploy: 
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: Initializing workspace
        run: |
          echo "Uploading to IEM"
          mkdir workspace
          cd workspace
          ie-app-publisher-linux ws init   
          cd ..      
          
      - name: Uploading app to IEM
        run: |
          echo "Uploading to IEM"
          cp -RT app ./workspace
          cd workspace
          ie-app-publisher-linux de c -u http://localhost:2375
          export IE_SKIP_CERTIFICATE=true
          ie-app-publisher-linux em li -u ${{secrets.IEM_URL}} -e ${{secrets.USER_NAME}} -p ${{secrets.PSWD}}
          ie-app-publisher-linux em app cuv -a ${{secrets.APP_ID}} -v 0.0.$GITHUB_RUN_NUMBER -y ./docker-compose.prod.yml -n '{"hello-edge":[{"name":"hello-edge","protocol":"HTTP","port":"80","headers":"","rewriteTarget":"/"}]}' -s 'hello-edge' -t 'FromBoxReverseProxy' -u "hello-edge" -r "/"
          ie-app-publisher-linux em app uuv -a ${{secrets.APP_ID}} -v 0.0.$GITHUB_RUN_NUMBER
